### PR TITLE
Adding Loader to required pages

### PR DESCRIPTION
**Pull request by aadarsh10c**
Added a pure CSS animated loader

### CODE REVIEW

**Comment by aadarsh10c** [comment]
@shaurya35

**Comment by shaurya35** [comment]
@aadarsh10c good work. There are few things I want you to add. 
1. Loaders are necessary where the web applications takes time to respond such as request from a database or verification
so please put loaders wherever required such as auth, companies, stocks, etc
2. Can you show a video of loader working, you may add some artificial delay just to test if the loader is working something like useEffect.

**Comment by aadarsh10c** [comment]
Sure @shaurya35 , I will send the video . Additionaly I will look into were u need addional Loaders.

**Comment by aadarsh10c** [comment]
@shaurya35 , The submit button of Signup and login forms will display a loading indicator upon click.Please check below and let me know if u want to keep or if u have any better  suggestions. 

https://github.com/user-attachments/assets/9d7ab149-37c3-4cde-bf63-f9865752e123

**Comment by shaurya35** [comment]
@aadarsh10c can you send me a video when it's showing the loading icon when a page is loaded, that's what I asked for.

**Comment by aadarsh10c** [comment]
@shaurya35 , here is the video . Here I have shown for Analytics dashboard(3 secs delay added), Same Loader has been added for 
Prediction and Chat.
https://github.com/user-attachments/assets/86a6f2ad-f607-4b4e-b151-795e695af8b7

**Comment by shaurya35** [comment]
@aadarsh10c good work with the login loading, but because to maintain the theme, the page loader should be somewhat similar to the theme. Can you please just put the loading loader and remove everything else.

Your PR will be merged after that.

- only the loading loader

**Comment by aadarsh10c** [comment]
@shaurya35 , sorry for late submission , I had a unavodialbe situation that needed my attention . Anyways, I have removed the Login loading , and have added only the loading  Loaders as shown above. Let me know if it needs any imporvements.

**Comment by shaurya35** [comment]
@aadarsh10c hello
By loading loader I meant the loader shown when login is clicked. 

Actually the page loader is not matching with the theme. 

If you can create a similar theme loader, then the pull request will resolve the issue. 

If I merge right now, the ui may get bonked for users. 

Key points:
- your login loader is good and can be merged
- page loader needs to be changed with specific ui and theme

**Comment by aadarsh10c** [comment]
@shaurya35 , hi
sry for the misundersatanding , I will make the changes by EOD.
Just fror confirmatioin , this the requested laoder right : https://github.com/shaurya35/Stockwise-Inventory-Manager/pull/29#issuecomment-2407133366

**Comment by shaurya35** [comment]
@aadarsh10c yeah you got it right

**Comment by aadarsh10c** [comment]
I have removed the page loader, and kept the login loader see #30 , Please close this pull request.

**Pull request closed without merging**
