### PR TITLE
modified routes

### PR DESCRIPTION
**Pull request by aadarsh10c**
Modify the App's page , add protection for other pages.

Solves #26

### CODE REVIEW

**Comment by shaurya35** [comment]
@aadarsh10c good work but point 2 is still unresolved.
image

please update this pull request with point 2 resolved, good work with point 1

**Comment by aadarsh10c** [comment]
@shaurya35 , regarding point 2  , I did not encounter it after doing the changes.

**Comment by aadarsh10c** [comment]
@shaurya35 , regarding point 2  , I did not encounter it after doing the changes

**Comment by aadarsh10c** [comment]
@shaurya35 , regarding point 2  , I did not enocunter it after doing the changes

**Comment by shaurya35** [comment]
@aadarsh10c aplogies for late reply, good work

**Pull request merged**
